apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-demo-external
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-store
    kind: SecretStore
  target:
    name: eso-demo-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: DB_PORT
    - secretKey: DB_USERNAME
      remoteRef:
        key: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
 
