apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-store
  namespace: default
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com # or eu.infisical.com
      auth:
        kubernetesAuthCredentials:
          identityId:
            key: identityId
            name: infisical-kubernetes-auth
            namespace: default
      secretsScope:
        projectSlug: kubernetes-secrets-demo-skie
        environmentSlug: dev
        secretsPath: /
