apiVersion: v1
kind: Service
metadata:
  name: eso-demo
  labels:
    app: eso-demo
spec:
  type: LoadBalancer
  selector:
    app: eso-demo
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
